project_name: testrepo
release:
  disable: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
- image_templates:
  - "razic/testrepo:{{ incpatch .Version }}-{{ .ShortCommit }}-amd64"
  use: buildx
  goarch: amd64
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "razic/testrepo:{{ incpatch .Version }}-{{ .ShortCommit }}-arm64"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: razic/testrepo:{{ .Version }}
  image_templates:
  - razic/testrepo:{{ .Version }}-amd64
  - razic/testrepo:{{ .Version }}-arm64
